/**
 * Seed data — predefined participants and ~18 realistic discussions
 * spread across every lifecycle stage. Loaded once on first DB open.
 *
 * Each participant has: rank (in `role` for now), function, and unit.
 * Participants with unit === "מצפן" are internal; others are external.
 */

import type { Discussion, Participant } from "@/types";

const now = Date.now();
const ISO = (offsetMs: number) => new Date(now + offsetMs).toISOString();
const HOUR = 3600_000;
const DAY = 24 * HOUR;

export const SEED_PARTICIPANTS: Participant[] = [
  // --- Internal (מצפן) ---
  { id: "p-amir",  name: "אמיר כהן",    role: 'אל"ם · ראש מטה',            unit: "מצפן" },
  { id: "p-noa",   name: "נועה לוי",    role: 'סא"ל · ראש מבצעים',         unit: "מצפן" },
  { id: "p-yair",  name: "יאיר אבני",   role: 'רס"ן · קצין מודיעין',       unit: "מצפן" },
  { id: "p-dana",  name: "דנה ברקת",    role: 'רס"ן · ראש תקשוב',          unit: "מצפן" },
  { id: "p-tomer", name: "תומר שגיא",   role: 'סא"ל · ראש לוגיסטיקה',      unit: "מצפן" },
  { id: "p-maya",  name: "מאיה גולן",   role: 'רס"ן · קצינת כ"א',          unit: "מצפן" },
  { id: "p-eitan", name: "איתן רוזן",   role: 'אל"ם · סגן מפקד',            unit: "מצפן" },
  { id: "p-ronit", name: "רונית פז",    role: 'רס"ן · קצינת מבצעים',       unit: "מצפן" },
  { id: "p-shira", name: "שירה אלון",   role: 'סרן · קצינת תוה"ד',          unit: "מצפן" },
  { id: "p-ido",   name: "עידו ברק",    role: "סרן · קצין מבצעים",          unit: "מצפן" },
  { id: "p-keren", name: "קרן שמש",     role: 'סא"ל · קצינת תכנון',        unit: "מצפן" },
  { id: "p-roi",   name: "רועי טל",     role: 'אל"ם · מפקד',                unit: "מצפן" },
  // --- External ---
  { id: "p-oren",  name: "אורן דגן",    role: 'סא"ל · ראש מדור',            unit: "אג\"ם — מטכ\"ל", external: true },
  { id: "p-gilad", name: "גלעד מזרחי",  role: 'סא"ל · קצין מודיעין בכיר',   unit: 'אמ"ן', external: true },
  { id: "p-hila",  name: "הילה ניר",    role: 'רס"ן · קצינת אבטחת מידע',    unit: "אגף תקשוב — מטכ\"ל", external: true },
  { id: "p-lior",  name: "ליאור אהרון", role: 'אל"ם · רע"ן מבצעים',         unit: "אוגדה 162", external: true },
  { id: "p-tal",   name: "טל פרידמן",   role: 'סא"ל · קצין קישור',          unit: "חיל האוויר", external: true },
  { id: "p-yael",  name: "יעל אדלר",    role: "רס\"ן · מתאמת",              unit: "משרד הבט\"ח", external: true },
];

type HistKind =
  | "created"
  | "status_changed"
  | "date_changed"
  | "participants_changed"
  | "leader_changed"
  | "summary_changed"
  | "note"
  | "attachment_added";

const hist = (kind: HistKind, text: string, daysAgo: number, by?: string) => ({
  id: `h-${Math.random().toString(36).slice(2, 9)}`,
  kind,
  at: ISO(-daysAgo * DAY),
  text,
  by,
});

let counter = 0;
const id = () => `disc-seed-${++counter}`;

export const SEED_DISCUSSIONS: Discussion[] = [
  // === REQUIRES SCHEDULING ===
  {
    id: id(),
    name: "סיכום שבועי — תמונת מצב מבצעית",
    status: "requires_scheduling",
    priority: "high",
    scheduledAt: null,
    participantIds: ["p-amir", "p-noa", "p-yair", "p-ronit"],
    leaderId: "p-noa",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "סיכום פעילות שבועי — להתאם בהקדם.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 1, "מזכירות")],
    createdAt: ISO(-1 * DAY),
    updatedAt: ISO(-1 * DAY),
  },
  {
    id: id(),
    name: 'תרגיל "רוח צפונית" — תיאום סופי',
    status: "requires_scheduling",
    priority: "urgent",
    scheduledAt: null,
    participantIds: ["p-eitan", "p-tomer", "p-oren", "p-gilad", "p-lior"],
    leaderId: "p-eitan",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: 'דחוף — נדרשת נוכחות לוגיסטיקה ונציגי אג"ם/אוגדה 162.',
    attachments: [],
    history: [hist("created", "הדיון נוצר", 2, "מזכירות")],
    createdAt: ISO(-2 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "תקציב רבעוני — דיון פתיחה",
    status: "requires_scheduling",
    priority: "normal",
    scheduledAt: null,
    participantIds: ["p-keren", "p-tomer", "p-amir"],
    leaderId: "p-keren",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    notes: "פתיחת תהליך תקציב Q3.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 4, "מזכירות")],
    createdAt: ISO(-4 * DAY),
    updatedAt: ISO(-4 * DAY),
  },
  {
    id: id(),
    name: "טיוב נהלי אבטחת מידע",
    status: "requires_scheduling",
    priority: "normal",
    scheduledAt: null,
    participantIds: ["p-dana", "p-hila", "p-yair"],
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: false,
    notes: "כולל הילה מאגף תקשוב במטכ\"ל. ליום שני אחה\"צ.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 0, "מזכירות")],
    createdAt: ISO(-6 * HOUR),
    updatedAt: ISO(-6 * HOUR),
  },

  // === SCHEDULED ===
  {
    id: id(),
    name: "תדריך בוקר מ\"פים",
    status: "scheduled",
    priority: "high",
    scheduledAt: ISO(2 * HOUR),
    participantIds: ["p-amir", "p-noa", "p-ronit", "p-ido"],
    leaderId: "p-amir",
    requiresSummary: false,
    requiresApproval: false,
    requiresDistribution: false,
    notes: "תדריך יומי — לא נדרש סיכום.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 3, "מזכירות"),
      hist("date_changed", "נקבע מועד", 3),
    ],
    createdAt: ISO(-3 * DAY),
    updatedAt: ISO(-3 * DAY),
  },
  {
    id: id(),
    name: "סטטוס ארגוני — מנהלי תחומים",
    status: "scheduled",
    priority: "normal",
    scheduledAt: ISO(1 * DAY + 3 * HOUR),
    participantIds: ["p-noa", "p-maya", "p-dana", "p-tomer"],
    leaderId: "p-noa",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    attachments: [
      { id: "att-1", name: "סדר יום.docx", kind: "file", addedAt: ISO(-DAY) },
    ],
    history: [
      hist("created", "הדיון נוצר", 5, "מזכירות"),
      hist("date_changed", "נקבע מועד", 5),
      hist("attachment_added", "סדר יום נוסף", 1, "נועה"),
    ],
    notes: "מנהלי תחומים בלבד.",
    createdAt: ISO(-5 * DAY),
    updatedAt: ISO(-1 * DAY),
  },
  {
    id: id(),
    name: "ביקור מפקד אוגדה",
    status: "scheduled",
    priority: "urgent",
    scheduledAt: ISO(2 * DAY + 5 * HOUR),
    participantIds: ["p-roi", "p-eitan", "p-amir", "p-noa", "p-keren", "p-lior"],
    leaderId: "p-roi",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "סיור + תדריך מטה. נציג אוגדה 162 יגיע יחד עם מפקד האוגדה.",
    attachments: [
      { id: "att-2", name: "מצגת ביקור.pptx", kind: "presentation", addedAt: ISO(-2 * DAY) },
    ],
    history: [
      hist("created", "הדיון נוצר", 7, "מזכירות"),
      hist("date_changed", "תאריך עודכן", 4),
    ],
    createdAt: ISO(-7 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "סקירת מודיעין שבועית",
    status: "scheduled",
    priority: "normal",
    scheduledAt: ISO(3 * DAY + 4 * HOUR),
    participantIds: ["p-gilad", "p-yair", "p-noa"],
    leaderId: "p-gilad",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    notes: 'כולל גלעד מאמ"ן.',
    attachments: [],
    history: [hist("created", "הדיון נוצר", 2, "מזכירות")],
    createdAt: ISO(-2 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "הכנה לתרגיל פיקוד",
    status: "scheduled",
    priority: "high",
    scheduledAt: ISO(5 * DAY + 2 * HOUR),
    participantIds: ["p-eitan", "p-oren", "p-tomer", "p-keren", "p-ronit", "p-tal"],
    leaderId: "p-oren",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "תיאום חצי-שנתי. כולל קצין קישור מחיל האוויר.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 6, "מזכירות")],
    createdAt: ISO(-6 * DAY),
    updatedAt: ISO(-6 * DAY),
  },

  // === WAITING FOR SUMMARY ===
  {
    id: id(),
    name: "סיכום אירוע מבצעי 19/04",
    status: "waiting_summary",
    priority: "urgent",
    scheduledAt: ISO(-2 * DAY),
    participantIds: ["p-noa", "p-yair", "p-amir", "p-eitan", "p-gilad"],
    leaderId: "p-yair",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "יאיר אחראי על הסיכום — לתזכר.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 5, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 2, "מזכירות"),
    ],
    createdAt: ISO(-5 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "בחינת תקלת תקשוב",
    status: "waiting_summary",
    priority: "normal",
    scheduledAt: ISO(-1 * DAY),
    participantIds: ["p-dana", "p-hila", "p-yair"],
    leaderId: "p-dana",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 3, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 1),
    ],
    createdAt: ISO(-3 * DAY),
    updatedAt: ISO(-1 * DAY),
  },
  {
    id: id(),
    name: "ועדת מינויים — דיון ראשון",
    status: "waiting_summary",
    priority: "high",
    scheduledAt: ISO(-3 * DAY),
    participantIds: ["p-maya", "p-amir", "p-keren"],
    leaderId: "p-maya",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: false,
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 8, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 3),
    ],
    createdAt: ISO(-8 * DAY),
    updatedAt: ISO(-3 * DAY),
  },

  // === WAITING APPROVAL ===
  {
    id: id(),
    name: "סיכום ישיבת סטטוס לוגיסטיקה",
    status: "waiting_approval",
    priority: "normal",
    scheduledAt: ISO(-4 * DAY),
    participantIds: ["p-tomer", "p-keren", "p-amir", "p-yael"],
    leaderId: "p-tomer",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    summary:
      "1. אושר תקציב חליפי לרכש מבצעי.\n2. הוחלט על העברת מלאי מזרח-צפון.\n3. עדכון תוכנית רכש עד 30/04.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 7, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 4),
      hist("summary_changed", "סיכום נכתב", 3, "תומר"),
    ],
    createdAt: ISO(-7 * DAY),
    updatedAt: ISO(-3 * DAY),
  },
  {
    id: id(),
    name: "סיכום ועדת מינויים",
    status: "waiting_approval",
    priority: "high",
    scheduledAt: ISO(-6 * DAY),
    participantIds: ["p-maya", "p-amir", "p-keren"],
    leaderId: "p-maya",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: false,
    summary: "סיכום ועדה — שלושה מינויים אושרו, אחד בבחינה.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 10, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 6),
      hist("summary_changed", "סיכום נכתב", 4),
    ],
    createdAt: ISO(-10 * DAY),
    updatedAt: ISO(-4 * DAY),
  },

  // === WAITING DISTRIBUTION ===
  {
    id: id(),
    name: "סיכום הדרכת אבטחת מידע",
    status: "waiting_distribution",
    priority: "normal",
    scheduledAt: ISO(-5 * DAY),
    participantIds: ["p-hila", "p-dana", "p-yair"],
    leaderId: "p-hila",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    summary:
      "ההדרכה התקיימה. הוחלט על מעבר נהלי גיבוי מורחבים החל מ-1/05.",
    attachments: [
      { id: "att-3", name: "סיכום_אבטחה.docx", kind: "summary", addedAt: ISO(-2 * DAY) },
    ],
    history: [
      hist("created", "הדיון נוצר", 9, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 5),
      hist("summary_changed", "סיכום נכתב", 4, "הילה"),
      hist("status_changed", "סיכום אושר", 2),
    ],
    createdAt: ISO(-9 * DAY),
    updatedAt: ISO(-2 * DAY),
  },

  // === COMPLETED ===
  {
    id: id(),
    name: "סיכום אירוע 03/04",
    status: "completed",
    priority: "high",
    scheduledAt: ISO(-12 * DAY),
    participantIds: ["p-eitan", "p-noa", "p-yair", "p-ronit"],
    leaderId: "p-eitan",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    summary: "האירוע סוכם והופץ לבעלי תפקידים.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 14, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 12),
      hist("summary_changed", "סיכום נכתב", 11),
      hist("status_changed", "אושר", 9),
      hist("status_changed", "הופץ", 8, "מזכירות"),
    ],
    createdAt: ISO(-14 * DAY),
    updatedAt: ISO(-8 * DAY),
  },
  {
    id: id(),
    name: 'ישיבת רס"רים',
    status: "completed",
    priority: "normal",
    scheduledAt: ISO(-9 * DAY),
    participantIds: ["p-keren", "p-shira", "p-ido"],
    leaderId: "p-keren",
    requiresSummary: false,
    requiresApproval: false,
    requiresDistribution: false,
    notes: "ישיבת עבודה — לא נדרש סיכום.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 11, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 9),
      hist("status_changed", "סומן כהושלם", 9),
    ],
    createdAt: ISO(-11 * DAY),
    updatedAt: ISO(-9 * DAY),
  },
  {
    id: id(),
    name: "סקירת תקלות תקשוב — מרץ",
    status: "completed",
    priority: "normal",
    scheduledAt: ISO(-15 * DAY),
    participantIds: ["p-dana", "p-hila"],
    leaderId: "p-dana",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    summary: "5 תקלות עיקריות, 3 נסגרו, 2 בטיפול. הסיכום הופץ.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 18, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 15),
      hist("summary_changed", "סיכום נכתב", 14),
      hist("status_changed", "הופץ", 12, "מזכירות"),
    ],
    createdAt: ISO(-18 * DAY),
    updatedAt: ISO(-12 * DAY),
  },
];
