/**
 * Seed data — predefined participants and 18 realistic discussions
 * spread across every lifecycle stage. Loaded once on first DB open.
 */

import type { Discussion, Participant } from "@/types";

const now = Date.now();
const ISO = (offsetMs: number) => new Date(now + offsetMs).toISOString();
const HOUR = 3600_000;
const DAY = 24 * HOUR;

export const SEED_PARTICIPANTS: Participant[] = [
  { id: "p-amir", name: "אמיר כהן", role: "אל\"ם", unit: "מטה" },
  { id: "p-noa", name: "נועה לוי", role: "סא\"ל", unit: "מבצעים" },
  { id: "p-yair", name: "יאיר אבני", role: "רס\"ן", unit: "מודיעין" },
  { id: "p-dana", name: "דנה ברקת", role: "רס\"ן", unit: "תקשוב" },
  { id: "p-tomer", name: "תומר שגיא", role: "סא\"ל", unit: "לוגיסטיקה" },
  { id: "p-maya", name: "מאיה גולן", role: "רס\"ן", unit: "כ\"א" },
  { id: "p-eitan", name: "איתן רוזן", role: "אל\"ם", unit: "פיקוד" },
  { id: "p-ronit", name: "רונית פז", role: "רס\"ן", unit: "מבצעים" },
  { id: "p-oren", name: "אורן דגן", role: "רס\"ן", unit: "אג\"ם" },
  { id: "p-shira", name: "שירה אלון", role: "סרן", unit: "תוה\"ד" },
  { id: "p-gilad", name: "גלעד מזרחי", role: "סא\"ל", unit: "מודיעין" },
  { id: "p-hila", name: "הילה ניר", role: "רס\"ן", unit: "תקשוב" },
  { id: "p-ido", name: "עידו ברק", role: "סרן", unit: "מבצעים" },
  { id: "p-keren", name: "קרן שמש", role: "סא\"ל", unit: "מטה" },
  { id: "p-roi", name: "רועי טל", role: "אל\"ם", unit: "פיקוד" },
];

const hist = (kind: any, text: string, daysAgo: number, by?: string) => ({
  id: `h-${Math.random().toString(36).slice(2, 9)}`,
  kind,
  at: ISO(-daysAgo * DAY),
  text,
  by,
});

let counter = 0;
const id = () => `disc-seed-${++counter}`;

export const SEED_DISCUSSIONS: Discussion[] = [
  // === REQUIRES SCHEDULING (top priority — always visible) ===
  {
    id: id(),
    name: "סיכום שבועי — תמונת מצב מבצעית",
    requester: "אל\"ם אמיר כהן",
    status: "requires_scheduling",
    priority: "high",
    scheduledAt: null,
    participantIds: ["p-amir", "p-noa", "p-yair", "p-ronit"],
    leaderId: "p-noa",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "סיכום פעילות שבועי — להתאם בהקדם.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 1, "מזכירות")],
    createdAt: ISO(-1 * DAY),
    updatedAt: ISO(-1 * DAY),
  },
  {
    id: id(),
    name: "תרגיל \"רוח צפונית\" — תיאום סופי",
    requester: "אל\"ם איתן רוזן",
    status: "requires_scheduling",
    priority: "urgent",
    scheduledAt: null,
    participantIds: ["p-eitan", "p-tomer", "p-oren", "p-gilad", "p-hila"],
    leaderId: "p-eitan",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "דיון דחוף — לתאם השבוע. נדרשת נוכחות לוגיסטיקה.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 2, "מזכירות")],
    createdAt: ISO(-2 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "תקציב רבעוני — דיון פתיחה",
    requester: "סא\"ל קרן שמש",
    status: "requires_scheduling",
    priority: "normal",
    scheduledAt: null,
    participantIds: ["p-keren", "p-tomer", "p-amir"],
    leaderId: "p-keren",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    notes: "פתיחת תהליך תקציב Q3.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 4, "מזכירות")],
    createdAt: ISO(-4 * DAY),
    updatedAt: ISO(-4 * DAY),
  },
  {
    id: id(),
    name: "טיוב נהלי תקשוב — מפגש ראשון",
    requester: "רס\"ן דנה ברקת",
    status: "requires_scheduling",
    priority: "normal",
    scheduledAt: null,
    participantIds: ["p-dana", "p-hila", "p-yair"],
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: false,
    notes: "המבקש ביקש שעה אחרי הצהריים.",
    attachments: [],
    history: [hist("created", "הדיון נוצר", 0, "מזכירות")],
    createdAt: ISO(-6 * HOUR),
    updatedAt: ISO(-6 * HOUR),
  },

  // === SCHEDULED (upcoming) ===
  {
    id: id(),
    name: "תדריך בוקר מ\"פים",
    requester: "אל\"ם אמיר כהן",
    status: "scheduled",
    priority: "high",
    scheduledAt: ISO(2 * HOUR), // today, soon
    durationMinutes: 30,
    participantIds: ["p-amir", "p-noa", "p-ronit", "p-ido"],
    leaderId: "p-amir",
    requiresSummary: false,
    requiresApproval: false,
    requiresDistribution: false,
    notes: "תדריך יומי — לא נדרש סיכום.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 3, "מזכירות"),
      hist("date_changed", "נקבע מועד", 3),
    ],
    createdAt: ISO(-3 * DAY),
    updatedAt: ISO(-3 * DAY),
  },
  {
    id: id(),
    name: "סטטוס ארגוני — מנהלי תחומים",
    requester: "סא\"ל נועה לוי",
    status: "scheduled",
    priority: "normal",
    scheduledAt: ISO(1 * DAY + 3 * HOUR), // tomorrow
    durationMinutes: 60,
    participantIds: ["p-noa", "p-maya", "p-dana", "p-tomer"],
    leaderId: "p-noa",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    attachments: [
      { id: "att-1", name: "סדר יום.docx", kind: "file", addedAt: ISO(-DAY) },
    ],
    history: [
      hist("created", "הדיון נוצר", 5, "מזכירות"),
      hist("date_changed", "נקבע מועד", 5),
      hist("attachment_added", "סדר יום נוסף", 1, "נועה"),
    ],
    notes: "מנהלי תחומים בלבד. נא להגיע עם סטטוס משימות.",
    createdAt: ISO(-5 * DAY),
    updatedAt: ISO(-1 * DAY),
  },
  {
    id: id(),
    name: "ביקור מפקד אוגדה",
    requester: "אל\"ם רועי טל",
    status: "scheduled",
    priority: "urgent",
    scheduledAt: ISO(2 * DAY + 5 * HOUR),
    durationMinutes: 90,
    participantIds: ["p-roi", "p-eitan", "p-amir", "p-noa", "p-keren"],
    leaderId: "p-roi",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "סיור + תדריך מטה. דרושה הצגה.",
    attachments: [
      { id: "att-2", name: "מצגת ביקור.pptx", kind: "presentation", addedAt: ISO(-2 * DAY) },
    ],
    history: [
      hist("created", "הדיון נוצר", 7, "מזכירות"),
      hist("date_changed", "תאריך עודכן", 4),
    ],
    createdAt: ISO(-7 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "סקירת מודיעין שבועית",
    requester: "סא\"ל גלעד מזרחי",
    status: "scheduled",
    priority: "normal",
    scheduledAt: ISO(3 * DAY + 4 * HOUR),
    durationMinutes: 45,
    participantIds: ["p-gilad", "p-yair", "p-noa"],
    leaderId: "p-gilad",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    attachments: [],
    history: [hist("created", "הדיון נוצר", 2, "מזכירות")],
    createdAt: ISO(-2 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "הכנה לתרגיל פיקוד",
    requester: "אל\"ם איתן רוזן",
    status: "scheduled",
    priority: "high",
    scheduledAt: ISO(5 * DAY + 2 * HOUR),
    durationMinutes: 120,
    participantIds: ["p-eitan", "p-oren", "p-tomer", "p-keren", "p-ronit"],
    leaderId: "p-oren",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    attachments: [],
    history: [hist("created", "הדיון נוצר", 6, "מזכירות")],
    createdAt: ISO(-6 * DAY),
    updatedAt: ISO(-6 * DAY),
  },

  // === WAITING FOR SUMMARY (meeting happened, summary pending) ===
  {
    id: id(),
    name: "סיכום אירוע מבצעי 19/04",
    requester: "סא\"ל נועה לוי",
    status: "waiting_summary",
    priority: "urgent",
    scheduledAt: ISO(-2 * DAY),
    durationMinutes: 60,
    participantIds: ["p-noa", "p-yair", "p-amir", "p-eitan"],
    leaderId: "p-yair",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    notes: "יאיר אחראי על הסיכום — לתזכר.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 5, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 2, "מזכירות"),
    ],
    createdAt: ISO(-5 * DAY),
    updatedAt: ISO(-2 * DAY),
  },
  {
    id: id(),
    name: "בחינת תקלת תקשוב",
    requester: "רס\"ן דנה ברקת",
    status: "waiting_summary",
    priority: "normal",
    scheduledAt: ISO(-1 * DAY),
    durationMinutes: 45,
    participantIds: ["p-dana", "p-hila", "p-yair"],
    leaderId: "p-dana",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 3, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 1),
    ],
    createdAt: ISO(-3 * DAY),
    updatedAt: ISO(-1 * DAY),
  },
  {
    id: id(),
    name: "ועדת מינויים — דיון ראשון",
    requester: "רס\"ן מאיה גולן",
    status: "waiting_summary",
    priority: "high",
    scheduledAt: ISO(-3 * DAY),
    durationMinutes: 90,
    participantIds: ["p-maya", "p-amir", "p-keren"],
    leaderId: "p-maya",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: false,
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 8, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 3),
    ],
    createdAt: ISO(-8 * DAY),
    updatedAt: ISO(-3 * DAY),
  },

  // === WAITING APPROVAL ===
  {
    id: id(),
    name: "סיכום ישיבת סטטוס לוגיסטיקה",
    requester: "סא\"ל תומר שגיא",
    status: "waiting_approval",
    priority: "normal",
    scheduledAt: ISO(-4 * DAY),
    durationMinutes: 60,
    participantIds: ["p-tomer", "p-keren", "p-amir"],
    leaderId: "p-tomer",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    summary:
      "1. אושר תקציב חליפי לרכש מבצעי.\n2. הוחלט על העברת מלאי מזרח-צפון.\n3. עדכון תוכנית רכש עד 30/04.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 7, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 4),
      hist("summary_changed", "סיכום נכתב", 3, "תומר"),
    ],
    createdAt: ISO(-7 * DAY),
    updatedAt: ISO(-3 * DAY),
  },
  {
    id: id(),
    name: "סיכום ועדת מינויים",
    requester: "רס\"ן מאיה גולן",
    status: "waiting_approval",
    priority: "high",
    scheduledAt: ISO(-6 * DAY),
    durationMinutes: 90,
    participantIds: ["p-maya", "p-amir", "p-keren"],
    leaderId: "p-maya",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: false,
    summary: "סיכום ועדה — שלושה מינויים אושרו, אחד בבחינה.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 10, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 6),
      hist("summary_changed", "סיכום נכתב", 4),
    ],
    createdAt: ISO(-10 * DAY),
    updatedAt: ISO(-4 * DAY),
  },

  // === WAITING DISTRIBUTION ===
  {
    id: id(),
    name: "סיכום הדרכת אבטחת מידע",
    requester: "רס\"ן הילה ניר",
    status: "waiting_distribution",
    priority: "normal",
    scheduledAt: ISO(-5 * DAY),
    durationMinutes: 60,
    participantIds: ["p-hila", "p-dana", "p-yair"],
    leaderId: "p-hila",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    summary:
      "ההדרכה התקיימה. הוחלט על מעבר נהלי גיבוי מורחבים החל מ-1/05.",
    attachments: [
      { id: "att-3", name: "סיכום_אבטחה.docx", kind: "summary", addedAt: ISO(-2 * DAY) },
    ],
    history: [
      hist("created", "הדיון נוצר", 9, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 5),
      hist("summary_changed", "סיכום נכתב", 4, "הילה"),
      hist("status_changed", "סיכום אושר", 2),
    ],
    createdAt: ISO(-9 * DAY),
    updatedAt: ISO(-2 * DAY),
  },

  // === COMPLETED ===
  {
    id: id(),
    name: "סיכום אירוע 03/04",
    requester: "אל\"ם איתן רוזן",
    status: "completed",
    priority: "high",
    scheduledAt: ISO(-12 * DAY),
    durationMinutes: 60,
    participantIds: ["p-eitan", "p-noa", "p-yair", "p-ronit"],
    leaderId: "p-eitan",
    requiresSummary: true,
    requiresApproval: true,
    requiresDistribution: true,
    summary: "האירוע סוכם והופץ לבעלי תפקידים.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 14, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 12),
      hist("summary_changed", "סיכום נכתב", 11),
      hist("status_changed", "אושר", 9),
      hist("status_changed", "הופץ", 8, "מזכירות"),
    ],
    createdAt: ISO(-14 * DAY),
    updatedAt: ISO(-8 * DAY),
  },
  {
    id: id(),
    name: "ישיבת רס\"רים",
    requester: "סא\"ל קרן שמש",
    status: "completed",
    priority: "normal",
    scheduledAt: ISO(-9 * DAY),
    durationMinutes: 45,
    participantIds: ["p-keren", "p-shira", "p-ido"],
    leaderId: "p-keren",
    requiresSummary: false,
    requiresApproval: false,
    requiresDistribution: false,
    notes: "ישיבת עבודה — לא נדרש סיכום.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 11, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 9),
      hist("status_changed", "סומן כהושלם", 9),
    ],
    createdAt: ISO(-11 * DAY),
    updatedAt: ISO(-9 * DAY),
  },
  {
    id: id(),
    name: "סקירת תקלות תקשוב — מרץ",
    requester: "רס\"ן דנה ברקת",
    status: "completed",
    priority: "normal",
    scheduledAt: ISO(-15 * DAY),
    durationMinutes: 60,
    participantIds: ["p-dana", "p-hila"],
    leaderId: "p-dana",
    requiresSummary: true,
    requiresApproval: false,
    requiresDistribution: true,
    summary: "5 תקלות עיקריות, 3 נסגרו, 2 בטיפול. הסיכום הופץ.",
    attachments: [],
    history: [
      hist("created", "הדיון נוצר", 18, "מזכירות"),
      hist("status_changed", "סומן כהתקיים", 15),
      hist("summary_changed", "סיכום נכתב", 14),
      hist("status_changed", "הופץ", 12, "מזכירות"),
    ],
    createdAt: ISO(-18 * DAY),
    updatedAt: ISO(-12 * DAY),
  },
];
